# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Corus Assessment
email: ivan@iloyola.com
description: > # this means to ignore newlines until "baseurl:"
  Front end developent Corus Assessment.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://iloyola.com/corus" # the base hostname & protocol for your site
linkedin_username: ivan-loyola-94b10a3
github_username:  iloyola

# Build settings
markdown: kramdown
exclude: ['node_modules', 'css', '_assets', 'gruntfile.js', 'package.json']
keep_files: ['index.html', '_site/css', '_site/js']
